version: '3'
services:
    app:
      image: phpswoole/swoole
      environment:
        AUTORELOAD_PROGRAMS: "swoole"
        AUTORELOAD_ANY_FILES: 0
      ports:
        - 80:9501
      volumes:
        - ./swoole:/var/www
    composer:
      image: "composer"
      volumes:
          - "./swoole/web/app:/app"
      command: install