version: '3'
services:
    app:
      environment:
        AUTORELOAD_PROGRAMS: "swoole"
        AUTORELOAD_ANY_FILES: 0
      build: .
      ports:
        - 80:9501
      volumes:
        - ./swoole:/var/www
        - ".env:/var/www/web/app/.env"
      depends_on:
        - mysqldb
    composer:
      image: "composer"
      volumes:
          - "./swoole/web/app:/app"
      command: install
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:${MYSQL_PORT}"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"